apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  selector:
    matchLabels:
      app: httpd  # Updated label
      tier: web   # Updated label
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd  # Updated label
        tier: web   # Updated label
    spec:
      containers:
        - name: httpd
          image: httpd:latest