apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nxginx  # Updated label
      tier: web   # Updated label
  replicas: 1
  template:
    metadata:
      labels:
        app: nxginx  # Updated label
        tier: web   # Updated label
    spec:
      containers:
        - name: nginx
          image: nginx:latest